### ISSUE TITLE
Ad Not Loading In 3G network

### ISSUE THREAD

**Issue by B1unty** [spotxmobile/spotx-sdk-android#1]
I have downloaded the sample app from the repository. It is working fine when I have WiFi network available but it is not working when I have mobile data on 3G/4G network .

I am getting an error
`com.spotxchange.demo E/MraidContainer: Received an invalid message from javascript AdBridge: org.json.JSONException: No value for url`

**Comment by bbiswal78** [comment]
I have the same issue. Does not work in 3G/4G. Please help.

**Comment by scottjulian** [comment]
Can you post the full debug log? Or tell me what urls the sdk is hitting? I want to know what url is being called to load our javascript as it seems to be sending an invalid event to our `MraidContainer`.

It is strange that this is happening on 3G. Curious, is it also happening on LTE as well?

**Comment by B1unty** [comment]
`06-17 03:30:25.611 19855-19898/com.spotxchange.demo D/SpotmarketRequestTask: Uri generated: 
                                                                             http://search.spotxchange.com/mraid/2.0/85394?prefetch=true&autoinit=false&autoplay=true&cb=1466141425320&ad_volume=1&app%5Bsdkversion%5D=2.0%20(2016061710)&device%5Bdpidsha1%5D=4dcb68ae-376d-4c8d-babc-dcebf469941c&app%5Bname%5D=SpotX%20SDK%20Demo&app%5Bversion%5D=2.0&app%5Bbundle%5D=com.spotxchange.demo&app%5Bdomain%5D=com.spotxchange.demo&device%5Bconnectiontype%5D=4&device%5Bos%5D=Android&device%5Bosv%5D=5.0.2&device%5Bmake%5D=LENOVO&device%5Bmodel%5D=Lenovo%20A6010&device%5Bdevicetype%5D=1&device%5Bgeo%5D%5Bcountry%5D=USA&device%5Bip%5D=fe80%3A%3Affc3%3Acdbf%3Aa3fd%3A8fb5%25rmnet_data0&device%5Bcarrier%5D=40476&device%5Bifa%5D=4dcb68ae-376d-4c8d-babc-dcebf469941c&device%5Blang%5D=en
06-17 03:30:27.236 19855-19855/com.spotxchange.demo D/NetworkChangeNotifierAutoDetect: Network connectivity changed, type is: 4
06-17 03:30:27.236 19855-19855/com.spotxchange.demo D/SpotmarketRequestTask: Request finished. 
06-17 03:30:27.236 19855-19855/com.spotxchange.demo D/SpotmarketResponseHandler: loading data from SpotMarket
06-17 03:30:27.524 19855-19855/com.spotxchange.demo D/NetworkChangeNotifierAutoDetect: Network connectivity changed, type is: 4
06-17 03:30:27.552 19855-19903/com.spotxchange.demo D/ConnectivityManager.CallbackHandler: CM callback handler got msg 524290
06-17 03:30:27.560 19855-19855/com.spotxchange.demo D/cr_Ime: [InputMethodManagerWrapper.java:30] Constructor
06-17 03:30:27.563 19855-19855/com.spotxchange.demo W/cr_AwContents: onDetachedFromWindow called when already detached. Ignoring
06-17 03:30:27.565 19855-19855/com.spotxchange.demo D/cr_Ime: [InputMethodManagerWrapper.java:59] isActive: false
06-17 03:30:27.668 19855-19855/com.spotxchange.demo I/cr_Ime: ImeThread is not enabled.
06-17 03:30:27.736 19855-19855/com.spotxchange.demo W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 19855
06-17 03:30:27.736 19855-19855/com.spotxchange.demo D/cr_Ime: [InputMethodManagerWrapper.java:59] isActive: false
06-17 03:30:29.129 19855-19903/com.spotxchange.demo D/ConnectivityManager.CallbackHandler: CM callback handler got msg 524290
06-17 03:30:29.138 19855-19903/com.spotxchange.demo D/ConnectivityManager.CallbackHandler: CM callback handler got msg 524290
06-17 03:30:29.647 19855-19855/com.spotxchange.demo I/chromium: [INFO:CONSOLE(198)] "MRAID Init", source: http://search.spotxchange.com/mraid.js (198)
06-17 03:30:29.675 19855-19855/com.spotxchange.demo D/MraidContainer: Initializing mraid bridge : (function(delegate, mraid){ mraid.initialize({"supports":{"sms":false,"tel":false,"calendar":true,"storePicture":true,"inlineVideo":true,"vpaid":true,"fireBeacon":true}}, function(msg) { delegate.sendMessage(msg); }, window.document); }(bridgeDelegate, window.mraid));
06-17 03:30:29.678 19855-19855/com.spotxchange.demo I/chromium: [INFO:CONSOLE(198)] "MRAID Init", source: http://search.spotxchange.com/mraid.js (198)
06-17 03:30:29.686 19855-19855/com.spotxchange.demo D/MraidContainer: onMessage: {"jsonrpc":"2.0","method":"sdk_loaded"}
06-17 03:30:29.760 19855-19855/com.spotxchange.demo D/MraidContainer: onMessage: {"jsonrpc":"2.0","method":"useCustomClose","params":{"state":true}}
06-17 03:30:30.144 19855-19855/com.spotxchange.demo I/chromium: [INFO:CONSOLE(0)] "The deviceorientation event is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.", source:  (0)
06-17 03:30:30.280 19855-19855/com.spotxchange.demo I/chromium: [INFO:CONSOLE(201)] "Bridge called with : {"width":720,"height":1232}", source: http://search.spotxchange.com/mraid.js (201)
06-17 03:30:50.274 19855-19855/com.spotxchange.demo D/MraidContainer: onMessage: {"jsonrpc":"2.0","method":"vpaidEvent","params":{"event":"AdError"}}
06-17 03:30:50.274 19855-19855/com.spotxchange.demo D/AdViewFragment: **Ad failed with error**
06-17 03:30:50.277 19855-19855/com.spotxchange.demo D/SpotxAdView: trying to set visibility to: 8
06-17 03:30:50.277 19855-19855/com.spotxchange.demo D/SpotxAdView: Visibility changed to GONE`

**Comment by scottjulian** [comment]
Thanks a lot for this. Also, I forgot to ask, what Android version is this happening on for you?

**Comment by bbiswal78** [comment]
I tried both on Marshmallow 6.0.1  and Lollypop 5.0.2

**Comment by B1unty** [comment]
I am facing the problem in lollipop 5.0.2

**Comment by lcniles** [comment]
@B1unty, @bbiswal78 -- Looking at the timestamps on the log that was provided, my guess is that this is a media timeout. Please contact your account manager, they will be able to adjust your timeout settings per channel to find the right balance that meets your needs. 

I'm closing this for now, but after following the above you stiff see issues, please feel free to re-open.

Thanks!
